#pragma once

#include "conan_global.h"
#include <QDir>
#include <QFileSystemWatcher>
#include <extensionsystem/iplugin.h>
#include <projectexplorer/projecttree.h>

class BuildInfo;
namespace ProjectExplorer {
  class EnvironmentAspect;
  class Target;
} // namespace ProjectExplorer

namespace conan {
  namespace Internal {

    class conanPlugin : public ExtensionSystem::IPlugin
    {
      Q_OBJECT
      Q_PLUGIN_METADATA(
          IID "org.qt-project.Qt.QtCreatorPlugin" FILE "conan.json")

    public:
      conanPlugin();
      ~conanPlugin();

      ///
      /// Execute conan install on the given conanFile path
      ///
      /// The provided directory must already exist, otherwise the behavior is
      /// undefined.
      /// \return A map containing the buildinfo generated by conan
      ///
      BuildInfo conanInstall(
          const QString& pathToConanFile, const QDir& directory);

      bool initialize(const QStringList& arguments, QString* errorString);
      void extensionsInitialized();
      ShutdownFlag aboutToShutdown();

      void setNewProject(ProjectExplorer::Project* project);

      void removeDepConnections();
      void updateDepConnections();

      ///
      /// Evaluate the dependency tree and set up the build directory
      ///
      /// Try to install the referenced requirements and create the dependency
      /// information.
      ///
      void setupBuildDirForce();
      void setupBuildDir(bool forceInstall);

      QString conanFilePath() const;

      ProjectExplorer::EnvironmentAspect* runEnvironmentAspect() const;

    private:
      void write(const QString& text) const;

      static ProjectExplorer::Target* currentTarget();

      QString currentBuildDir() const;

      class PluginConfig
      {
      private:
        QString _conanFilePath;
        QString _installFlags;
        bool _useLibPath;
        bool _useBinPath;

      public:
        PluginConfig() = default;
        PluginConfig(const QString& path, const QString& installFlags,
            const bool useBinPath, const bool useLibPath)
            : _conanFilePath {path}, _installFlags {installFlags},
              _useLibPath {useLibPath}, _useBinPath {useBinPath}
        {
        }
        bool useLibraryPathAsEnvironmentPath() const
        {
          return _useLibPath;
        }
        bool useBinaryPathAsEnvironmentPath() const
        {
          return _useBinPath;
        }
        bool isAutoDetect() const
        {
          return _conanFilePath.isEmpty();
        }

        QString conanFile() const
        {
          return _conanFilePath;
        }

        QString installFlags() const
        {
          return _installFlags;
        }
      };

      PluginConfig _config;

    private:
      QString _lastInstallDir;
      QFileSystemWatcher _conanFileWatcher;
      QChar _pathSeparator;
      std::list< QMetaObject::Connection > _depConnections;
    };

  } // namespace Internal
} // namespace conan
