#pragma once

#include "conan_global.h"
#include <QDir>
#include <QFileSystemWatcher>
#include <extensionsystem/iplugin.h>
#include <projectexplorer/projecttree.h>

namespace conan {
  namespace Internal {

    class conanPlugin : public ExtensionSystem::IPlugin
    {
      Q_OBJECT
      Q_PLUGIN_METADATA(
          IID "org.qt-project.Qt.QtCreatorPlugin" FILE "conan.json")

    public:
      conanPlugin();
      ~conanPlugin();

      ///
      /// Execute conan install on the given conanFile path
      ///
      /// The provided directory must already exist, otherwise the behavior is
      /// undefined.
      /// \return A map containing the buildinfo generated by conan
      ///
      QVariantMap conanInstall(
          const QString& pathToConanFile, const QDir& directory) const;

      bool initialize(const QStringList& arguments, QString* errorString);
      void extensionsInitialized();
      ShutdownFlag aboutToShutdown();

      void setNewProject(ProjectExplorer::Project* project);

      void updateDepConnections();

      ///
      /// Evaluate the dependency tree and set up the build directory
      ///
      /// Try to install the referenced requirements and create the dependency
      /// information.
      ///
      void evaluateDependencies();

      QString conanFilePath() const;

    private:
      void write(const QString& text) const;

      QString currentBuildDir() const;

      class PluginConfig
      {
      private:
        QString _conanFilePath;
        QString _installFlags;

      public:
        PluginConfig() = default;
        PluginConfig(const QString& path, const QString& installFlags)
            : _conanFilePath {path}, _installFlags {installFlags}
        {
        }

        bool isAutoDetect() const
        {
          return _conanFilePath.isEmpty();
        }

        QString conanFile() const
        {
          return _conanFilePath;
        }

        QString installFlags() const
        {
          return _installFlags;
        }
      };

      PluginConfig _config;

    private:
      QFileSystemWatcher _conanFileWatcher;
      QChar _pathSeparator;
      std::list< QMetaObject::Connection > _depConnections;
    };

  } // namespace Internal
} // namespace conan
